### ISSUE TITLE
Stacking Widget: NoneType Object is not callable

### ISSUE THREAD

**Issue by oyvinrog** [biolab/orange3-prototypes#112]
##### Prototypes version

0.8.0

##### Orange version

3.8

##### Expected behavior

Stacking widget should function as a learner as input for "Test & Score"

##### Actual behavior

NoneType failed with error: TypeError

![image](https://user-images.githubusercontent.com/16526012/34688593-ecf8d4b4-f4b2-11e7-8790-17dc11ea0e59.png)

##### Steps to reproduce the behavior

- Create random forest learner
- Create kNN learner

- try to combine into Stacking widget

- Add to "Test & Score"

**Comment by ajdapretnar** [comment]
This is because Stacking also requires an aggregate function, say a Logistic Regression which you can bring in and edit the connection to Learner - Aggregate.
The proper procedure is described in [this blog post](https://blog.biolab.si/2018/01/05/stack-everything/) and the documentation is coming soon (say, 2 days).

**Comment by ajdapretnar** [comment]
@lanzagar Would it make sense to set LogReg as a default aggregate function and then keep Aggregate input to override it if desired?

**Comment by oyvinrog** [comment]
Thank you! It now works with Test & Score. The results seem very promising. The AUC is great. However, I was unable to make stacking work with the "Predictions" widget. The "Predictions" widget has 

1) Current data to make predictions about 
2) My best models (as model->predictors)
3) The stacking widget (as model->predictors)

the stacking widget line becomes stapled when I attempt to use it. I have tried to disable/enable the line, but it does not work.

![image](https://user-images.githubusercontent.com/16526012/34690983-72dd5b56-f4bb-11e7-8b2e-295089ff16a8.png)

**Comment by ajdapretnar** [comment]
This is because Predictions require a model instead of a learner. And each model needs data to be built. Hence you need to input the data for building a model into Stacking widget. Please see the documentation for Predictions for an example on regular models.

Also, when you are posting screenshots of issues, I'd suggest you post the entire workflow, since it is easier to determine where the problem is. Thank you!

**Comment by ajdapretnar** [comment]
@oyvinrog Can we consider this issue closed?

**Comment by oyvinrog** [comment]
yes, the stacking widget works perfectly now. My model got really good improvement in prediction accuracy because of it. Im now able to predict the BTC price. Thanks!!!
